### ISSUE TITLE
which binutils release for gcc-4.6.4-mint

### ISSUE THREAD

**Issue by paulwratt** [freemint/m68k-atari-mint-binutils-gdb#3]
Will the latest (only?) binutils-2.30 binary release work with [gcc-4.6.4-mint](https://github.com/freemint/m68k-atari-mint-gcc/releases/tag/gcc-4_6_4-mint) (18 Apr 2017). If not which source package is the appropriate version, and will it be suitable if built with [gcc-7.4.0-mint](https://github.com/freemint/m68k-atari-mint-gcc/releases/tag/gcc-7_4_0-mint-20190228)

**Comment by vinriviere** [comment]
Any binutils version from the last 10 years should work fine with gcc-4.6.4-mint.
